export const SITUACION_TRABAJADOR = ['ACTIVO', 'INACTIVO', 'JUBILADO', 'REPOSO', 'PERMISO', 'SUSPENDIDO', 'COMISION DE SERVICIO'];
export const FUNCIONES_PERSONAL = ['DOCENTE', 'DIRECTOR', 'SUBDIRECTOR', 'COORDINADOR', 'ORIENTADOR', 'EVALUADOR', 'SECRETARIA', 'ASISTENTE', 'PORTERO', 'ASEADOR', 'VIGILANTE', 'MADRE COCINERA'];
export const TIPO_PERSONAL = ['DOCENTE', 'ADMINISTRATIVO', 'OBRERO'];
export const MATERIAS_COMUNES = ['CASTELLANO', 'MATEMATICA', 'FISICA', 'QUIMICA', 'BIOLOGIA', 'INGLES', 'GEOGRAFIA', 'HISTORIA', 'EDUCACION FISICA', 'ARTES PLASTICAS', 'INFORMATICA', 'ORIENTACION'];

export const EJES_CONSOLIDACION_OPCIONES = [
  { value: 'EJE_INICIAL_PRIMARIA', label: 'EJE INICIAL Y PRIMARIA' },
  { value: 'EJE_MEDIA_TECNICA', label: 'EJE MEDIA Y TECNICA' },
  { value: 'EJE_ESPECIAL', label: 'EJE EDUCACION ESPECIAL' },
  { value: 'EJE_ADULTOS', label: 'EJE EDUCACION ADULTOS' },
  { value: 'MISIONES', label: 'MISIONES EDUCATIVAS' }
];

export const TALLAS_CAMISA = ['SS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'];
export const TALLAS_PANTALON = ['26', '28', '30', '32', '34', '36', '38', '40', '42', '44', '46'];
export const TIPOS_VIVIENDA = ['CASA', 'APARTAMENTO', 'ANEXO', 'RANCHO', 'HABITACION', 'QUINTA'];
export const CONDICION_VIVIENDA = ['PROPIA', 'ALQUILADA', 'PRESTADA', 'INVADIDA', 'PAGANDO', 'ADJUDICADA'];
export const NIVELES_INSTRUCCION = ['BACHILLER', 'TSU', 'LICENCIADO / PROFESOR', 'MAGISTER', 'DOCTORADO', 'ESPECIALIZACION', 'NINGUNO'];

export const CARGOS = ['DIRECTOR', 'SUBDIRECTOR', 'COORDINADOR', 'DOCENTE DE AULA', 'DOCENTE ESPECIALISTA', 'ADMINISTRATIVO', 'OBRERO', 'MADRE COCINERA', 'VIGILANTE'];
