
export const DEPENDENCIAS = ['Nacional', 'Estadal', 'Municipal', 'Privado', 'Subvencionada', 'Autónoma'];
export const NIVELES = ['Maternal', 'Preescolar', 'Primaria', 'Media General', 'Media Técnica'];
export const MODALIDADES = ['Fronterizos', 'Especial', 'Adultos', 'Intercultural'];
export const TURNOS = ['Mañana', 'Tarde', 'Integral', 'Nocturno', 'Sabatino'];
export const CARGOS = ['Administrativo', 'Docente', 'Tutor FUNDABIT', 'Cocinera', 'Aseador', 'Vigilante'];
export const TIPO_PERSONAL = ['ADMINISTRATIVO', 'DOCENTE', 'OBRERO'];
export const FUNCIONES_PERSONAL = ['ADMINISTRATIVO', 'DOCENTE', 'ASEADOR', 'COCINERO', 'VIGILANTE', 'DIRECTOR', 'SUBDIRECTOR', 'COORDINADOR', 'SUPERVISOR', 'CHOFER', 'DIRECTOR CDCEM', 'COORDINADOR CDCEM', 'SUPERVISOR CDCEM'];
export const SITUACION_TRABAJADOR = ['ACTIVO', 'ABANDONO DE CARGO', 'CAMBIO DE ACTIVIDAD', 'CLAUSULA', 'COMISION DE SERVICIO', 'DEFUNCION', 'INCAPACIDAD', 'INCAPACIDAD PARCIAL', 'JUBILACION', 'RENUNCIA', 'REPOSO CONTINUO', 'REPOSO PARCIAL', 'SANCION ADMINISTRATIVA', 'SUSPENSION', 'TRAM. INCAPACIDAD', 'TRAM. JUBILACION', 'TRASLADO'];

export const TALLAS_CAMISA = ['S', 'M', 'L', 'XL', 'XXL', '3XL'];
export const TALLAS_PANTALON = ['28', '30', '32', '34', '36', '38', '40', '42', '44'];
export const TIPOS_VIVIENDA = ['CASA', 'APARTAMENTO', 'QUINTA', 'RANCHO', 'ANEXO', 'HABITACIÓN'];
export const CONDICION_VIVIENDA = ['PROPIA', 'ALQUILADA', 'DE UN FAMILIAR', 'OTRO'];
export const NIVELES_INSTRUCCION = ['PRIMARIA', 'BACHILLER', 'TSU', 'LICENCIADO', 'MAGISTER', 'DOCTORADO'];

export const SUBJECTS_31059 = [
    'CASTELLANO', 'INGLES', 'MATEMATICA', 'ED. FISICA', 'ARTE Y PATRIMONIO',
    'CIENCIAS NATURALES', 'BIOLOGIA', 'FISICA', 'QUIMICA', 'GEOGRAFIA, HISTORIA',
    'ORIENTACION', 'G.C.R.P.'
];

export const SUBJECTS_31060 = [
    'LENGUA Y LITERATURA', 'IDIOMAS', 'MATEMATICA', 'ED. FISICA', 'BIOLOGIA/AMBIENTE',
    'FISICA', 'QUIMICA', 'GEOGRAFIA/HISTORIA', 'ORIENTACION VOC.', 'INNOVACION TECN.',
    'PROYECTO CIENTIFICO'
];

export const SUBJECTS_TECNICA = [
    'LENGUA Y LIT.', 'IDIOMAS', 'MATEMATICA', 'ED. FISICA', 'BIOLOGIA/AMBIENTE',
    'FISICA', 'QUIMICA', 'GEO. HISTORIA', 'DIBUJO TECNICO', 'TALLER ESPECIFICO',
    'TECNOLOGIA', 'PRACTICA PROF.'
];

export const SUBJECTS_TECNICA_BLANCO = [
    'ASIGNATURA 1', 'ASIGNATURA 2', 'ASIGNATURA 3', 'ASIGNATURA 4',
    'COMPONENTE TEC. 1', 'COMPONENTE TEC. 2', 'COMPONENTE TEC. 3',
    'TALLER / LAB', 'PROYECTO', 'PASANTIAS'
];

export const MATERIAS_COMUNES = ['Matemática', 'Física', 'Química', 'Biología', 'Castellano', 'Inglés', 'Geografía, Historia y Ciudadanía', 'Educación Física', 'Arte y Patrimonio', 'Ciencias Naturales', 'Orientación y Convivencia', 'Grupos de Creación', 'Integral (Primaria)'];

export const EJES_CONSOLIDACION_OPCIONES = [
    { value: 'EJE_INICIAL_PRIMARIA', label: 'Hoja 1: Maternal, Inicial, Primaria' },
    { value: 'EJE_ESPECIAL', label: 'Hoja 2: Educación Especial (Formato Único)' },
    { value: 'EJE_MEDIA_31059', label: 'Hoja 4: Plan 31059 (Media General)' },
    { value: 'EJE_MEDIA_31060', label: 'Hoja 3: Plan 31060 (Ciencia y Tecnología)' },
    { value: 'EJE_TECNICA', label: 'Plan de Estudio Técnica Profesional' },
    { value: 'EJE_ADULTOS', label: 'Hoja 5: Adultos' }
];

export const CUADRATURA_IP_CONFIG = [
    { label: 'MATERNAL', key: 'MAT', subs: ['G1', 'G2', 'G3', 'G4'] },
    { label: 'INICIAL', key: 'INI', subs: ['A', 'B', 'C', 'D', 'E'] },
    { label: '1ER GRADO', key: '1G', subs: ['A', 'B', 'C', 'D', 'E'] },
    { label: '2DO GRADO', key: '2G', subs: ['A', 'B', 'C', 'D', 'E'] },
    { label: '3ER GRADO', key: '3G', subs: ['A', 'B', 'C', 'D', 'E'] },
    { label: '4TO GRADO', key: '4G', subs: ['A', 'B', 'C', 'D', 'E'] },
    { label: '5TO GRADO', key: '5G', subs: ['A', 'B', 'C', 'D', 'E'] },
    { label: '6TO GRADO', key: '6G', subs: ['A', 'B', 'C', 'D', 'E'] }
];

export const CUADRATURA_ESPECIAL_COLUMNS = [
    'GRUPO 1', 'GRUPO 2', 'GRUPO 3', 'GRUPO 4', 'GRUPO 5', 'GRUPO 6',
    'GRUPO 7', 'GRUPO 8', 'GRUPO 9', 'GRUPO 10', 'GRUPO 11', 'GRUPO 12'
];

export const ADULTOS_PERIODOS_ESTANDAR = [
    { label: '1ER PERIODO', key: 'P1', subjects: ['LENGUA Y COMUNICACION', 'IDIOMAS', 'MATEMATICA', 'CIENCIAS BIOLOGICAS', 'GEO-HIST-CIUD.', 'ORIENTACION Y CONVIVENCI.'] },
    { label: '2DO PERIODO', key: 'P2', subjects: ['LENGUA Y COMUNICACION', 'IDIOMAS', 'MATEMATICA', 'CIENCIAS BIOLOGICAS', 'GEO-HIST-CIUD.', 'ORIENTACION Y CONVIVENCI.'] },
    { label: '3ER PERIODO', key: 'P3', subjects: ['LENGUA Y COMUNICACION', 'IDIOMAS', 'MATEMATICA', 'CIENCIAS BIOLOGICAS', 'QUIMICA', 'GEO-HIST-CIUD.', 'ORIENTACION Y CONVIVENCI.'] },
    { label: '4TO PERIODO', key: 'P4', subjects: ['LENGUA Y COMUNICACION', 'IDIOMAS', 'MATEMATICA', 'CIENCIAS BIOLOGICAS', 'QUIMICA', 'GEO-HIST-CIUD.', 'ORIENTACION Y CONVIVENCI.'] },
    { label: '5TO PERIODO', key: 'P5', subjects: ['LENGUA Y COMUNICACION', 'IDIOMAS', 'MATEMATICA', 'CIENCIAS BIOLOGICAS', 'QUIMICA', 'GEO-HIST-CIUD.', 'ORIENTACION Y CONVIVENCI.'] },
    { label: '6TO PERIODO', key: 'P6', subjects: ['LENGUA Y COMUNICACION', 'IDIOMAS', 'MATEMATICA', 'CIENCIAS BIOLOGICAS', 'QUIMICA', 'GEO-HIST-CIUD.', 'ORIENTACION Y CONVIVENCI.'] },
];

export const ADULTOS_PERIODOS_BLANCO = [
    { label: '1ER PERIODO', key: 'P1', subjects: Array.from({length: 8}, (_, i) => `OPCION ${i+1}`) },
    { label: '2DO PERIODO', key: 'P2', subjects: Array.from({length: 8}, (_, i) => `OPCION ${i+1}`) },
    { label: '3ER PERIODO', key: 'P3', subjects: Array.from({length: 8}, (_, i) => `OPCION ${i+1}`) },
    { label: '4TO PERIODO', key: 'P4', subjects: Array.from({length: 8}, (_, i) => `OPCION ${i+1}`) },
    { label: '5TO PERIODO', key: 'P5', subjects: Array.from({length: 8}, (_, i) => `OPCION ${i+1}`) },
    { label: '6TO PERIODO', key: 'P6', subjects: Array.from({length: 8}, (_, i) => `OPCION ${i+1}`) },
];

export const TIPOS_ESPACIOS = [{ key: 'oficinas', label: 'Oficinas Administrativas' }, { key: 'pasillos', label: 'Pasillos' }, { key: 'salones', label: 'Salones de Clase' }, { key: 'depositos', label: 'Depósitos' }, { key: 'cocina', label: 'Cocina / Comedor' }, { key: 'patio', label: 'Patio Central' }, { key: 'plazoleta', label: 'Plazoleta' }, { key: 'jardines', label: 'Jardines / Áreas Verdes' }, { key: 'cancha', label: 'Cancha Deportiva' }, { key: 'banos', label: 'Baños' }, { key: 'multiuso', label: 'Espacio de Usos Múltiples' }, { key: 'estacionamiento', label: 'Estacionamiento' }, { key: 'cbit', label: 'CBIT / Sala Telemática' }, { key: 'anfiteatro', label: 'Anfiteatro / Auditorio' }, { key: 'biblioteca', label: 'Biblioteca' }];
export const PROVEEDORES_INTERNET = ['CANTV', 'ON-LINK', 'FIBEX', 'TECNO NET', 'UP LINK', 'MAS PLANET', 'MULTICANAL', 'VNET', 'SATELCA', 'LG TELECOM', 'OTRO'];
export const TIPOS_CONEXION = ['ABA CANTV', 'FIBRA CANTV', 'FIBRA OPTICA', 'SATELITAL', 'INALAMBRICA', 'OTRO'];
export const STATUS_CONEXION = ['Activa', 'Averia', 'Solicitud', 'OTRO'];
export const ZONAS_UBICACION = ['URBANA', 'RURAL', 'DIFICIL ACCESO', 'INSULAR', 'INDIGENA', 'FRONTERA'];
export const VIAS_ACCESO = ['Terrestre', 'Fluvial', 'Aereo', 'Maritimo'];

export const UTENSILIOS_COCINA = ['Ollas Grandes', 'Sartenes', 'Cubiertos', 'Platos', 'Vasos', 'Bandejas', 'Cuchillos', 'Otras herramientas'];
export const ARTEFACTOS_ELECTRICOS = ['Nevera', 'Congelador', 'Cocina Industrial', 'Licuadora Industrial', 'Reverbero', 'Microondas', 'Horno'];
export const TIPOS_ALIMENTO = ['Seco', 'Proteína', 'Verduras/Hortalizas'];
export const CONDICION_USO = ['Apto', 'Por Vencer', 'No Apto', 'Bueno', 'Regular', 'Malo', 'Operativo', 'No Operativo'];
export const CONDICION_BIEN = ['BUENO', 'REGULAR', 'MALO', 'DESINCORPORAR', 'FALTANTE', 'EN REPARACION'];

export const TIPOS_ESTRUCTURA = ['EDIFICACIÓN VERTICAL', 'EDIFICACIÓN HORIZONTAL', 'RURAL', 'MÓDULO'];
export const ESTADO_INFRAESTRUCTURA = ['BUENO', 'REGULAR', 'MALO', 'CRITICO'];
export const SERVICIOS_AGUA = ['DIRECTA (TUBERÍA)', 'CISTERNA', 'POZO PROFUNDO', 'NO POSEE'];
export const SERVICIOS_ELECTRICIDAD = ['ESTABLE', 'INESTABLE', 'SIN SERVICIO', 'PLANTA ELÉCTRICA'];
export const SERVICIOS_AGUAS_SERVIDAS = ['RED DE CLOACAS', 'POZO SÉPTICO', 'SIN SERVICIO'];
export const SERVICIOS_GAS = ['BOMBONA (CILINDRO)', 'GAS DIRECTO', 'BOMBONA INDUSTRIAL'];
export const ESTATUS_SOLICITUD = ['Sin Solicitud', 'Enviada', 'Aprobada', 'En Ejecución', 'Culminada'];
export const ESTATUS_OBRA = ['No Iniciada', 'En Ejecución', 'Paralizada', 'Culminada'];

export const MATERIAS_NECESIDAD_MG = SUBJECTS_31059;
export const MATERIAS_NECESIDAD_MT_BASICA = SUBJECTS_31060;
export const MATERIAS_NECESIDAD_CT_31060 = SUBJECTS_TECNICA;

export const GEOGRAFIA_VENEZUELA: Record<string, Record<string, string[]>> = {
  "AMAZONAS": {
    "ALTO ORINOCO": ["LA ESMERALDA", "HUACHAMACARE", "MARAWAKA", "MAVACA", "SIERRA PARIMA"],
    "ATABAPO": ["SAN FERNANDO DE ATABAPO", "UCATA", "YAPACANA", "CANAME"],
    "ATURES": ["FERNANDO GIRON TOVAR", "LUIS ALBERTO GOMEZ", "PAHUACENNA", "PARHUEÑA", "PLATANAL"],
    "AUTANA": ["SAMARIAPO", "SIPAPO", "MUNDUAPO", "GUAYAPO"],
    "MANAPIARE": ["ALTO VENTUARI", "MEDIO VENTUARI", "BAJO VENTUARI"],
    "MAROA": ["MAROA", "VICTORINO", "COMUNIDAD"],
    "RIO NEGRO": ["SAN CARLOS DE RIO NEGRO", "COCUY", "SOLANO"]
  },
  "ANZOATEGUI": {
    "ANACO": ["ANACO", "SAN JOAQUIN"],
    "ARAGUA": ["ARAGUA DE BARCELONA", "CACHIPO"],
    "FERNANDO DE PEÑALVER": ["PUERTO PIRITU", "SAN MIGUEL", "SUCRE"],
    "FRANCISCO DE MIRANDA": ["ATAPIRIRE", "BOCA DE PAO", "EL PAO DE BARCELONA", "PARIAGUAN"],
    "FRANCISCO DEL CARMEN CARVAJAL": ["SANTA BARBARA", "VALLE DE GUANAPE"],
    "GUANIPA": ["SAN JOSE DE GUANIPA"],
    "GUANTA": ["GUANTA", "CHORRERON"],
    "INDEPENDENCIA": ["MAMO", "SOLEDAD"],
    "JOSE GREGORIO MONAGAS": ["MAPIRE", "PIAR", "SAN DIEGO DE CABRUTICA", "SANTA CLARA", "UVERITO", "ZUATA"],
    "JUAN ANTONIO SOTILLO": ["POZUELOS", "PUERTO LA CRUZ"],
    "JUAN MANUEL CAJIGAL": ["ONOTO", "SAN PABLO"],
    "LIBERTAD": ["EL CARITO", "SAN MATEO", "SANTA INES"],
    "MANUEL EZEQUIEL BRUZUAL": ["CLARINES", "GUANAPE", "SABANA DE UCHIRE"],
    "PEDRO MARIA FREITES": ["CANTAURA", "SAN TOME", "LIBERTADOR", "SANTA ROSA", "URICA"],
    "PIRITU": ["SAN FRANCISCO", "PIRITU"],
    "SAN JUAN DE CAPISTRANO": ["BOCA DE CHAVEZ", "BOCA DE UCHIRE"],
    "SANTA ANA": ["PUEBLO NUEVO", "SANTA ANA"],
    "SIMON BOLIVAR": ["BERGANTIN", "CAIGUA", "EL CARMEN", "EL PILAR", "NARICUAL", "SAN CRISTOBAL"],
    "SIMON RODRIGUEZ": ["EDMUNDO BARRIOS", "MIGUEL OTERO SILVA"],
    "SIR ARTHUR MAC GREGOR": ["EL CHAPARRO", "TOMAS ALFARO CALATRAVA"],
    "URBANEJA": ["LECHERIA"]
  },
  "APURE": {
    "ACHAGUAS": ["ACHAGUAS", "APURITO", "EL YAGUAL", "GUACHARA", "MUCURITAS", "QUESERAS DEL MEDIO"],
    "BIRUACA": ["BIRUACA"],
    "MUNOZ": ["BRUZUAL", "MANTECAL", "QUINTERO", "RINCON HONDO", "SAN VICENTE"],
    "PAEZ": ["GUASDUALITO", "ARAMENDI", "EL AMPARO", "SAN CAMILO", "URDANETA"],
    "PEDRO CAMEJO": ["SAN JUAN DE PAYARA", "CODAZZI", "CUNAVICHE"],
    "ROMULO GALLEGOS": ["ELORZA", "LA TRINIDAD"],
    "SAN FERNANDO": ["SAN FERNANDO", "EL RECREO", "PENALVER", "SAN RAFAEL DE ATAMAICA"]
  },
  "ARAGUA": {
    "BOLIVAR": ["SAN MATEO"],
    "CAMATAGUA": ["CAMATAGUA", "CARMEN DE CURA"],
    "FRANCISCO LINARES ALCANTARA": ["SANTA RITA", "FRANCISCO DE MIRANDA", "MONSENOR FELICIANO GONZALEZ"],
    "GIRARDOT": ["PEDRO JOSE OVALLES", "JOAQUIN CRESPO", "JOSE CASANOVA GODOY", "MADRE MARIA DE SAN JOSE", "ANDRES ELOY BLANCO", "LOS TACARIGUAS", "LAS DELICIAS", "CHORONI"],
    "JOSE ANGEL LAMAS": ["SANTA CRUZ"],
    "JOSE FELIX RIBAS": ["JOSE FELIX RIBAS", "CASTOR NIEVES RIOS", "LAS GUACAMAYAS", "PAO DE ZARATE", "ZUARTA"],
    "JOSE R REVENGA": ["JOSE RAFAEL REVENGA"],
    "LIBERTADOR": ["SAN MARTIN DE PORRES", "PALO NEGRO"],
    "MARIO B IRAGORRY": ["EL LIMON", "CAÑA DE AZUCAR"],
    "OCUMARE DE LA COSTA DE ORO": ["OCUMARE DE LA COSTA"],
    "SAN CASIMIRO": ["SAN CASIMIRO", "VALLE MORIN"],
    "SAN SEBASTIAN": ["SAN SEBASTIAN"],
    "SANTIAGO MARINO": ["TURMERO", "AREVALO APONTE", "CHUAO", "SAMAN DE GUERE", "ALFREDO PACHECO MIRANDA"],
    "SUCRE": ["CAGUA", "BELLA VISTA"],
    "TOVAR": ["COLONIA TOVAR"],
    "URDANETA": ["BARBACOAS", "SAN FRANCISCO DE CARA", "TAGUAY", "LAS PENITAS"],
    "ZAMORA": ["VILLA DE CURA", "MAGDALENO", "SAN FRANCISCO DE ASIS", "VALLES DE TUCUTUNEMO", "AUGUSTO MIJARES"]
  },
  "BARINAS": {
    "ALBERTO ARVELO TORREALBA": ["SABANETA", "JUAN ANTONIO RODRIGUEZ DOMINGUEZ"],
    "ANDRES ELOY BLANCO": ["EL CANTON", "SANTA CRUZ DE GUACAS", "PUERTO VIVAS"],
    "ANTONIO JOSE DE SUCRE": ["TICOPORO", "NICOLAS PULIDO", "ANDRES BELLO"],
    "ARISMENDI": ["ARISMENDI", "GUADARRAMA", "LA UNION", "SAN ANTONIO"],
    "BARINAS": ["BARINAS", "ALBERTO ARVELO LARRIVA", "SAN SILVESTRE", "SANTA INES", "SANTA LUCIA", "TORUNOS", "EL CARMEN", "ROMULO BETANCOURT", "CORAZON DE JESUS", "RAMON IGNACIO MENDEZ", "ALTO BARINAS", "MANUEL PALACIO FAJARDO", "JUAN ANTONIO RODRIGUEZ DOMINGUEZ", "DOMINGA ORTIZ DE PAEZ"],
    "BOLIVAR": ["BARINITAS", "ALTAMIRA DE CACERES", "CALDERAS"],
    "CRUZ PAREDES": ["BARRANCAS", "EL SOCORRO", "MASPARRITO"],
    "EZEQUIEL ZAMORA": ["SANTA BARBARA", "PEDRO BRICENO MENDEZ", "RAMON IGNACIO MENDEZ", "JOSE IGNACIO DEL PUMAR"],
    "OBISPOS": ["OBISPOS", "GUADARRAMA", "EL REAL", "LA LUZ"],
    "PEDRAZA": ["CIUDAD BOLIVIA", "JOSE IGNACIO DEL PUMAR", "JOSE FELIX RIBAS", "PAEZ"],
    "ROJAS": ["LIBERTAD", "DOLORES", "PALACIOS FAJARDO", "SANTA ROSA"],
    "SOSA": ["CIUDAD DE NUTRIAS", "EL REGALO", "PUERTO NUTRIAS", "SANTA CATALINA"]
  },
  "BOLIVAR": {
    "CARONI": ["CACHAMAY", "CHIRICA", "DALLA COSTA", "ONOTO", "PANAPANA", "POZO VERDE", "PUERTO ORDAZ", "SIMON BOLIVAR", "UNARE", "VISTA AL SOL", "YUOCOIMA"],
    "CEDENO": ["CAICARA DEL ORINOCO", "ALTAGRACIA", "ASCENSION FARRERAS", "GUANIAMO", "LA URBANA", "PIJIGUAOS"],
    "EL CALLAO": ["EL CALLAO"],
    "GRAN SABANA": ["SANTA ELENA DE UAIREN", "IKABARU"],
    "HERES": ["CATEDRAL", "AGUA SALADA", "JOSE ANTONIO PAEZ", "MARHUANTA", "ORINOCO", "PANAPANA", "VISTA HERMOSA", "ZEA"],
    "PIAR": ["CAPITAL PIAR", "ANDRES ELOY BLANCO", "PEDRO COVA"],
    "RAUL LEONI": ["CIUDAD PIAR", "ARICAGUA", "BARCELONETA", "SAN FRANCISCO"],
    "ROSCIO": ["GUASIPATI", "SALOM"],
    "SIFONTES": ["TUMEREMO", "DALLA COSTA", "SAN ISIDRO"],
    "SUCRE": ["MARIPA", "ARIPAO", "GUARATARO", "LAS MAJADAS", "MOITACO"],
    "PADRE PEDRO CHIEN": ["EL PALMAR"]
  },
  "CARABOBO": {
    "BOLIVAR": ["BELEN"],
    "CARABOBO": ["CARABOBO"],
    "CARLOS ARVELO": ["GUIGUE", "BELEN", "TACARIGUA"],
    "DIEGO IBARRA": ["MARIARA", "AGUAS CALIENTES", "SAN JOAQUIN"],
    "GUACARA": ["GUACARA", "CIUDAD ALIANZA", "YAGUA"],
    "JUAN JOSE MORA": ["MARIARA", "AGUAS CALIENTES"],
    "LIBERTADOR": ["TOCUYITO", "INDEPENDENCIA"],
    "LOS GUAYOS": ["LOS GUAYOS"],
    "MIRANDA": ["MIRANDA"],
    "MONTAlBAN": ["MONTALBAN"],
    "NAGUANAGUA": ["NAGUANAGUA"],
    "PUERTO CABELLO": ["BARTOLOME SALOM", "DEMOCRACIA", "FRATERNIDAD", "GOAIGOAZA", "JUAN JOSE FLORES", "UNION", "BORBURATA", "PATANEMO"],
    "SAN DIEGO": ["SAN DIEGO"],
    "SAN JOAQUIN": ["SAN JOAQUIN"],
    "VALENCIA": ["CANDELARIA", "CATEDRAL", "EL SOCORRO", "MIGUEL PENA", "RAFAEL URDANETA", "SAN BLAS", "SAN JOSE", "SANTA ROSA", "NEGRO PRIMERO"]
  },
  "COJEDES": {
    "ANZOATEGUI": ["COJEDES", "JUAN DE MATA SUAREZ"],
    "FALCON": ["TINAQUILLO", "MACAPO"],
    "GIRARDOT": ["EL BAUL", "SUCRE"],
    "LIMA BLANCO": ["MACAPO", "LA AGUADITA"],
    "PAO DE SAN JUAN BAUTISTA": ["EL PAO"],
    "RICAURTE": ["LIBERTAD DE COJEDES", "EL AMPARO"],
    "ROMULO GALLEGOS": ["LAS VEGAS"],
    "SAN CARLOS": ["SAN CARLOS DE AUSTRIA", "JUAN ANGEL BRAVO", "MANUEL MANRIQUE"],
    "TINAQUILLO": ["TINAQUILLO"]
  },
  "DELTA AMACURO": {
    "ANTONIO DIAZ": ["CURIAPO", "ALMIRANTE LUIS BRION", "FRANCISCO ANICETO LUGO", "MANUEL RENAUD", "PADRE BARRAL", "SANTOS DE ABELGAS"],
    "CASACOIMA": ["IMATACA", "CINCO DE JULIO", "JUAN BAUTISTA ARISMENDI", "MANUEL PIAR", "ROMULO GALLEGOS"],
    "PEDERNALES": ["PEDERNALES", "LUIS BELTRAN PRIETO FIGUEROA"],
    "TUCUPITA": ["TUCUPITA", "JOSE VIDAL MARCANO", "JUAN MILLAN", "LEONARDO RUIZ PINEDA", "MARISCAL ANTONIO JOSE DE SUCRE", "MONSENOR ARGIMIRO GARCIA", "SAN JOSE", "SAN RAFAEL", "VIRGEN DEL VALLE"]
  },
  "DISTRITO CAPITAL": {
    "LIBERTADOR": ["ALTAGRACIA", "ANTIMANO", "CANDELARIA", "CARICUAO", "CATEDRAL", "COCHE", "EL RECREO", "EL VALLE", "LA PASTORA", "LA VEGA", "MACARAO", "MACARAO", "EL JUNQUITO", "PARAISO", "PETARE", "SAN AGUSTIN", "SAN BERNARDINO", "SAN JOSE", "SAN JUAN", "SAN PEDRO", "SANTA ROSALIA", "SANTA TERESA", "SUCRE", "23 DE ENERO"]
  },
  "FALCON": {
    "ACOSTA": ["SAN JUAN DE LOS CAYOS", "CAPADARE", "LA PASTORA", "LIBERTADOR"],
    "BOLIVAR": ["SAN LUIS", "ARACUA", "LA PENA"],
    "BUCHIVACOA": ["CAPATARIDA", "BOROJO", "SEQUE", "ZAZARIDA", "BARIRO", "GUAJIRO"],
    "CACIQUE MANAURE": ["YARACAL"],
    "CARIRUBANA": ["NORTE", "CARIRUBANA", "SANTA ANA", "PUNTA CARDON"],
    "COLINA": ["LA VELA DE CORO", "ACURIGUA", "GUAIBACOA", "MACORUCA", "LAS CALDERAS"],
    "DABAJURO": ["DABAJURO", "AGUA CLARA", "SAN JOSE DE SEQUE"],
    "DEMOCRACIA": ["PEDREGAL", "AGUA CLARA", "AVELINA DE ROMERO", "PURURECHE", "TUPURE"],
    "FALCON": ["PUEBLO NUEVO", "ADICORA", "BARAIVED", "BUENA VISTA", "EL VINCULO", "EL HATO", "MORUY", "JADACAQUIVA"],
    "FEDERACION": ["CHURUGUARA", "AGUA LARGA", "EL PAUJI", "INDEPENDENCIA", "MAPARARI"],
    "JACURA": ["JACURA", "AGUA LINDA", "ARAURIMA"],
    "LOS TAQUES": ["LOS TAQUES", "JUDIBANA"],
    "MAUROA": ["MENE DE MAUROA", "CASIGUA", "SAN FELIX"],
    "MIRANDA": ["SAN ANTONIO", "SAN GABRIEL", "SANTA ANA", "GUZMAN GUILLERMO", "MITARE", "SABANETA"],
    "MONSENOR ITURRIZA": ["CHICHIRIVICHE", "BOCA DE TOCUYO", "TOCUYO DE LA COSTA"],
    "PALMASOLA": ["PALMASOLA"],
    "PETIT": ["CABURE", "COLINA", "CURIMAGUA"],
    "PIRITU": ["PIRITU", "SAN JOSE DE LA COSTA"],
    "SAN FRANCISCO": ["MIRIMIRE"],
    "SILVA": ["TUCACAS", "BOCA DE AROA"],
    "SUCRE": ["LA CRUZ DE TARATARA", "PECAYA"],
    "TOCOPERO": ["TOCOPERO"],
    "UNION": ["SANTA CRUZ DE BUCARAL", "EL CHARAL", "LAS VEGAS DEL TUY"],
    "URUMACO": ["URUMACO"],
    "ZAMORA": ["PUERTO CUMAREBO", "LA CIENAGA", "LA SOLEDAD", "PUEBLO CUMAREBO", "ZAZARIDA"]
  },
  "GUARICO": {
    "CAMAGUAN": ["CAMAGUAN", "PUERTO MIRANDA", "UVERITO"],
    "CHAGUARAMAS": ["CHAGUARAMAS"],
    "EL SOCORRO": ["EL SOCORRO"],
    "FRANCISCO DE MIRANDA": ["CALABOZO", "EL CALVARIO", "EL RASTRO", "GUARDATINAJAS"],
    "JOSE FELIX RIBAS": ["TUCUPIDO", "SAN RAFAEL DE LAYA"],
    "JOSE TADEO MONAGAS": ["ALTAGRACIA DE ORITUCO", "LEZAMA", "LIBERTAD DE ORITUCO", "MACAIRA", "PASO REAL DE MACAIRA", "SAN FRANCISCO DE MACAIRA", "SAN RAFAEL DE ORITUCO"],
    "JUAN GERMAN ROSCIO": ["SAN JUAN DE LOS MORROS", "CANTAGALLO", "PARAPARA"],
    "JULIAN MELLADO": ["EL SOMBRERO", "SOSA"],
    "LAS MERCEDES": ["LAS MERCEDES", "CABRUTA", "SANTA RITA DE MANAPIRE"],
    "LEONARDO INFANTE": ["VALLE DE LA PASCUA", "ESPINO"],
    "ORTIZ": ["ORTIZ", "SAN FRANCISCO DE TIZNADOS", "SAN JOSE DE TIZNADOS", "SAN LORENZO DE TIZNADOS"],
    "PEDRO ZARAZA": ["ZARAZA", "SAN JOSE DE UNARE"],
    "SAN GERONIMO DE GUAYABAL": ["GUAYABAL", "CAZUCA"],
    "SAN JOSE DE GUARIBE": ["SAN JOSE DE GUARIBE"],
    "SANTA MARIA DE IPIRE": ["SANTA MARIA DE IPIRE", "ALTAMIRA"]
  },
  "LARA": {
    "ANDRES ELOY BLANCO": ["SANARE", "PIO TAMAYO", "YACAMBU"],
    "CRESPO": ["DUACA", "JOSE MARIA BLANCO"],
    "IRIBARREN": ["CATEDRAL", "CONCEPCION", "EL CUJI", "JUAN DE VILLEGAS", "SANTA ROSA", "TAMACA", "UNION", "AGUEDO FELIPE ALVARADO", "BUENA VISTA", "JUAREZ"],
    "JIMENEZ": ["QUIBOR", "CUARA", "DIEGO DE LOZADA", "PARAISO DE SAN JOSE", "SAN MIGUEL", "TINTORERO"],
    "MORAN": ["EL TOCUYO", "ANZOATEGUI", "BOLIVAR", "GUARICO", "HILARIO LUNA Y LUNA", "HUMOCARO ALTO", "HUMOCARO BAJO", "LA ESTADISTICA"],
    "PALAVECINO": ["CABUDARE", "AGUA VIVA", "JOSE BERNARDO DORANTE"],
    "SIMON PLANAS": ["SARARE", "BURIA", "GUSTAVO VEGAS LEON"],
    "TORRES": ["EL TOCUYO", "ALTAGRACIA", "ANTONIO DIAZ", "CAMACARO", "CASTANEDA", "CECILIO ZUBILLAGA", "CHIQUINQUIRA", "EL BLANCO", "ESPINOZA DE LOS MONTEROS", "LARA", "LAS MERCEDES", "MANUEL MORILLO", "MONTANA VERDE", "MONTES DE OCA", "REYES VARGAS", "TORRES", "TRINIDAD SAMUEL"],
    "URDANETA": ["SIQUISIQUE", "MOROTURO", "SAN MIGUEL", "XAGUAS"]
  },
  "MERIDA": {
    "ALBERTO ADRIANI": ["GABRIEL PICON GONZALEZ", "HECTOR AMABLE MORA", "JOSE NUCETE SARDI", "OMICIO", "PRESIDENTE BETANCOURT", "PRESIDENTE PAEZ", "ROMULO GALLEGOS"],
    "ANDRES BELLO": ["LA AZULITA"],
    "ANTONIO PINTO SALINAS": ["SANTA CRUZ DE MORA", "MESA BOLIVAR", "MESA DE LAS PALMAS"],
    "ARICAGUA": ["ARICAGUA", "SAN ANTONIO"],
    "ARZOBISPO CHACON": ["CANAGUA", "CAPURI", "CHACANTA", "EL MOLINO", "GUAIMARAL", "MUCUTUY", "MUCUCHACHI"],
    "CAMPO ELIAS": ["FERNANDEZ PENA", "MATRIZ", "MONTALBAN", "ACEQUIAS", "JAJI", "LA MESA", "SAN JOSE DEL SUR"],
    "CARACCIOLO PARRA OLMEDO": ["TUCANI", "FLORENCIO RAMIREZ"],
    "CARDENAL QUINTERO": ["TIMOTES", "PIÑANGO", "LAS PIEDRAS"],
    "GUARAQUE": ["GUARAQUE", "MESA DE QUINTERO", "RIO NEGRO"],
    "JULIO CESAR SALAS": ["ARAPUEY", "PALMIRA"],
    "JUSTO BRICENO": ["TORONDOY", "SAN CRISTOBAL DE TORONDOY"],
    "LIBERTADOR": ["ANTONIO SPINETTI DINI", "ARIAS", "CARACCIOLO PARRA PEREZ", "DOMINGO PENA", "EL LLANO", "JUAN RODRIGUEZ SUAREZ", "JACINTO PLAZA", "MARIANO PICON SALAS", "OSUNA RODRIGUEZ", "SAGRARIO", "EL MORRO", "GONZALO PICON FEBRES", "LASS LA GUARDIA", "LOS NEVADOS", "MUCUUNUTAN"],
    "MIRANDA": ["TIMOTES", "ANDRES ELOY BLANCO", "LA VENTA", "PIÑANGO"],
    "OBISPO RAMOS DE LORA": ["SANTA ELENA DE ARENALES", "ELOY PAREDES", "SAN RAFAEL DE ALCAZAR"],
    "PADRE NOGUERA": ["SANTA MARIA DE CAPARO"],
    "PUEBLO LLANO": ["PUEBLO LLANO"],
    "RANGEL": ["MUCUCHIES", "CACUTE", "LA TOMA", "MUCURUBA", "SAN RAFAEL"],
    "RIVAS DAVILA": ["BAILADORES", "GERONIMO MALDONADO"],
    "SANTOS MARQUINA": ["MUCUCHIES", "CACUTE", "LA TOMA", "MUCURUBA", "SAN RAFAEL"],
    "SUCRE": ["LAGUNILLAS", "CHIGUARA", "ESTANQUES", "LA TRAMPA", "PUEBLO NUEVO DEL SUR", "SAN JUAN"],
    "TOVAR": ["TOVAR", "EL AMPARO", "EL LLANO", "SAN FRANCISCO"],
    "TULIO FEBRES CORDERO": ["NUEVA BOLIVIA", "INDEPENDENCIA", "MARIA DE LA CONCEPCION PALACIOS BLANCO", "SANTA APOLONIA"],
    "ZEA": ["ZEA", "CAÑO EL TIGRE"]
  },
  "MIRANDA": {
    "ACEVEDO": ["CAUCAGUA", "ARAGUITA", "AREVALO GONZALEZ", "CAPAYA", "CUMBO", "EL CAFE", "MARIZAPA", "PANAQUIRE", "RIBAS"],
    "ANDRES BELLO": ["SAN JOSE DE BARLOVENTO", "CUMBO"],
    "BARUTA": ["EL CAFETAL", "LAS MINAS DE BARUTA", "NUESTRA SEÑORA DEL ROSARIO DE BARUTA"],
    "BRION": ["HIGUEROTE", "CURIEPE", "TACARIGUA"],
    "BUROZ": ["MAMPORAL"],
    "CARRIZAL": ["CARRIZAL"],
    "CHACAO": ["BARUTA", "CHACAO", "EL CAFETAL"],
    "CRISTOBAL ROJAS": ["SAN ANTONIO DE LOS ALTOS"],
    "EL HATILLO": ["EL HATILLO"],
    "GUAICAIPURO": ["LOS TEQUES", "ALTAGRACIA DE LA MONTAÑA", "CECILIO ACOSTA", "EL JARILLO", "PARACOTOS", "SAN PEDRO", "TACATA"],
    "INDEPENDENCIA": ["SANTA TERESA DEL TUY", "EL CARTANAL"],
    "LANDER": ["OCUMARE DEL TUY", "LA DEMOCRACIA", "SANTA BARBARA"],
    "LOS SALIAS": ["SAN ANTONIO DE LOS ALTOS"],
    "PAEZ": ["RIO CHICO", "EL GUAPO", "TACARIGUA DE LA LAGUNA", "PAPARO", "SAN FERNANDO DEL GUAPO"],
    "PAZ CASTILLO": ["SANTA LUCIA"],
    "PEDRO GUAL": ["CUPIRA", "MACHURUCUCA"],
    "PLAZA": ["GUARENAS"],
    "SIMON BOLIVAR": ["SAN FRANCISCO DE YARE", "SAN ANTONIO DE YARE"],
    "SUCRE": ["LEONCIO MARTINEZ", "PETARE", "CAUCAGUITA", "FILAS DE MARICHE", "LA DOLORITA"],
    "URDANETA": ["CUA", "NUEVA CUA"],
    "ZAMORA": ["GUATIRE", "BOLIVAR"]
  },
  "MONAGAS": {
    "ACOSTA": ["SAN ANTONIO DE MATURIN", "SAN FRANCISCO DE MATURIN"],
    "AGUASAY": ["AGUASAY"],
    "BOLIVAR": ["CARIPITO"],
    "CARIPE": ["CARIPE", "EL GUACHARO", "LA GUANOTA", "SABANA DE PIEDRA", "SAN AGUSTIN", "TERESEN"],
    "CEDENO": ["CAICARA", "AREO", "SAN FELIX", "VISTRAL"],
    "EZEQUIEL ZAMORA": ["PUNTA DE MATA", "EL TEJERO"],
    "LIBERTADOR": ["TEMBLADOR", "CHAGUARAMAS", "LAS ALHUACAS", "TABASCA"],
    "MATURIN": ["ALTO DE LOS GODOS", "BOQUERON", "LAS COCUIZAS", "SAN SIMON", "SANTA CRUZ", "EL COROZO", "EL FURRIAL", "JUSEPIN", "LA PICA", "SAN VICENTE"],
    "PIAR": ["ARAGUA DE MATURIN", "CHAGUARAMAL", "EL PINTO", "GUANAGUANA", "LA TORENA", "TAGUAYA"],
    "PUNCERES": ["QUIRIQUIRE", "CACHIPO"],
    "SANTA BARBARA": ["SANTA BARBARA"],
    "SOTILLO": ["BARRANCAS", "LOS BARRANCOS DE FAJARDO"],
    "URACOA": ["URACOA"]
  },
  "NUEVA ESPARTA": {
    "ANTOLIN DEL CAMPO": ["LA PLAZA DE PARAGUACHI"],
    "ARISMENDI": ["LA ASUNCION"],
    "DIAZ": ["SAN JUAN BAUTISTA", "ZABALA"],
    "GARCIA": ["EL VALLE DEL ESPIRITU SANTO", "FRANCISCO FAJARDO"],
    "GOMEZ": ["SANTA ANA", "SUCRE", "BOLIVAR", "MATASIETE"],
    "MANEIRO": ["PAMPATAR", "AGUIRRE"],
    "MARCANO": ["JUAN GRIEGO", "ADRIAN"],
    "MARIÑO": ["PORLAMAR"],
    "PENINSULA DE MACANAO": ["BOCA DEL RIO", "SAN FRANCISCO"],
    "TUBORES": ["PUNTA DE PIEDRAS", "LOS BARALES"],
    "VILLALBA": ["SAN PEDRO DE COCHE", "VICENTE FUENTES"]
  },
  "PORTUGUESA": {
    "AGUA BLANCA": ["AGUA BLANCA"],
    "ARAURE": ["ARAURE", "RIO ACARIGUA"],
    "ESTELLER": ["PIRITU", "UVERAL"],
    "GUANARE": ["GUANARE", "CORDOBA", "SAN JOSE DE LA MONTANA", "SAN JUAN DE GUANAGUANARE", "VIRGEN DE COROMOTO"],
    "GUANARITO": ["GUANARITO", "TRINIDAD DE LA CAPILLA", "DIVINA PASTORA"],
    "MONSENOR JOSE VICENTE DE UNDA": ["PENA BLANCA"],
    "OSPINO": ["OSPINO", "APARICION", "LA ESTACION"],
    "PAEZ": ["ACARIGUA", "PAYARA", "PIMPINELA", "RAMON PERAZA"],
    "PAPELON": ["PAPELON", "CAÑO DELGADITO"],
    "SAN GENARO DE BOCONOITO": ["BOCONOITO", "ANTOLIN TOVAR AQUINO"],
    "SAN RAFAEL DE ONOTO": ["SAN RAFAEL DE ONOTO", "SANTA FE", "THERMO"],
    "SANTA ROSALIA": ["EL PLAYON", "FLORIDA"],
    "SUCRE": ["BISCUCUY", "CONCEPCION", "SAN RAFAEL DE PALO ALZADO", "UVIQUITO", "VILLA ROSA", "SAN JOSE DE SAGUAZ"],
    "TURÉN": ["VILLA BRUZUAL", "CANELONES", "SANTA CRUZ", "SAN ISIDRO LABRADOR"]
  },
  "SUCRE": {
    "ANDRES ELOY BLANCO": ["CASANAY", "MARIGUITAR"],
    "ANDRES MATA": ["SAN JOSE DE AEROCUAL", "TAVERA ACOSTA"],
    "ARISMENDI": ["RIO CARIBE", "ANTONIO JOSE DE SUCRE", "EL MORRO", "PUERTO SANTO", "SAN JUAN DE LAS GALDONAS"],
    "BENITEZ": ["EL PILAR", "EL RINCON", "GENERAL FRANCISCO ANTONIO VALDEZ", "GUARAUNOS", "TUNAPUICITO", "UNION"],
    "BERMUDEZ": ["SANTA CATALINA", "SANTA ROSA", "MACARAPANA", "BOLIVAR", "MACURO"],
    "BOLIVAR": ["MARIGUITAR"],
    "CAJIGAL": ["YAGUARAPARO", "EL PAUJI", "LIBERTAD"],
    "CRUZ SALMERON ACOSTA": ["ARAYA", "CHACOPATA", "MANICUARE"],
    "LIBERTADOR": ["TUNAPUY", "CAMPO CLARO"],
    "MARINO": ["IRAPA", "CAMPO CLARO", "MARABAL", "SAN ANTONIO DE IRAPA", "SORO"],
    "MEJIA": ["SAN ANTONIO DEL GOLFO"],
    "MONTES": ["CUMANACOA", "ARENAS", "ARICAGUA", "COCOLLAR", "SAN FERNANDO", "SAN LORENZO"],
    "RIBERO": ["CARIACO", "CATUARO", "RENDON", "SANTA CRUZ", "SANTA MARIA"],
    "SUCRE": ["ALTAGRACIA", "SANTA INES", "VALENTIN VALIENTE", "AYACUCHO", "SAN JUAN", "RAUL LEONI", "GRAN MARISCAL"],
    "VALDEZ": ["GUIRIA", "BIDEAU", "CRISTOBAL COLON", "PUNTA DE PIEDRAS"]
  },
  "TACHIRA": {
    "ANDRES BELLO": ["CORDERO"],
    "ANTONIO ROMULO COSTA": ["LAS MESAS"],
    "AYACUCHO": ["COLON", "RIVAS BECERRA", "SAN PEDRO DEL RIO"],
    "BOLIVAR": ["SAN ANTONIO DEL TACHIRA", "PALOTAL", "GENERAL CIPRIANO CASTRO", "ISAIS MEDINA ANGARITA"],
    "CARDENAS": ["TARIBA", "AMENODORO RANGEL LAMUS", "LA FLORIDA"],
    "CORDOBA": ["SANTA ANA DEL TACHIRA"],
    "FERNANDEZ FEO": ["SAN RAFAEL DEL PINAL", "ALBERTO ADRIANI", "SANTO DOMINGO"],
    "FRANCISCO DE MIRANDA": ["SAN JOSE DE BOLIVAR"],
    "GARCIA DE HEVIA": ["LA FRIA", "BOCA DE GRITA", "JOSE ANTONIO PAEZ"],
    "GUASIMOS": ["PALMIRA"],
    "INDEPENDENCIA": ["CAPACHO NUEVO", "JUAN GERMAN ROSCIO", "ROMAN CARDENAS"],
    "JAUREGUI": ["LA GRITA", "EMILIO CONSTANTINO GUERRERO", "MONSENOR MIGUEL ANTONIO SALAS"],
    "JOSE MARIA VARGAS": ["EL COBRE"],
    "JUNIN": ["RUBIO", "PETALEA", "QUINIMARI"],
    "LIBERTAD": ["CAPACHO VIEJO", "CIPRIANO CASTRO", "MANUEL FELIPE RUGELES"],
    "LIBERTADOR": ["ABEJALES", "DORADAS", "EMETERIO OCHOA", "SAN JOAQUIN DE NAVAY"],
    "LOBATERA": ["LOBATERA", "CONSTITUCION"],
    "MICHELENA": ["MICHELENA"],
    "PANAMERICANO": ["COLONCITO", "LA PALMITA"],
    "PEDRO MARIA URENA": ["URENA", "NUEVA ARCADIA"],
    "RAFAEL URDANETA": ["DELICIAS"],
    "SAMUEL DARIO MALDONADO": ["LA TENDIDA", "BOCONO", "HERNANDEZ"],
    "SAN CRISTOBAL": ["LA CONCORDIA", "SAN JUAN BAUTISTA", "PEDRO MARIA MORANTES", "SAN SEBASTIAN", "FRANCISCO ROMERO LOBO"],
    "SEBORUCO": ["SEBORUCO"],
    "SIMON BOLIVAR": ["SAN SIMON"],
    "SUCRE": ["QUENIQUEA", "ELEAZAR LOPEZ CONTRERAS", "SAN PABLO"],
    "TORBES": ["SAN JOSECITO"],
    "URIBANTE": ["PREGONERO", "CARDENAS", "JUAN PABLO PENALOZA", "POTOSI"]
  },
  "TRUJILLO": {
    "ANDRES BELLO": ["SANTA ISABEL", "ARAGUANEY", "EL JAGUITO", "LA ESPERANZA"],
    "BOCONO": ["BOCONO", "EL CARMEN", "MOSQUEY", "AYACUCHO", "BURBUSA", "GENERAL RIVAS", "GUARAMACAL", "VEGA DE GUARAMACAL", "MONSENOR JAUREGUI", "RAFAEL RANGEL", "SAN JOSE", "SAN MIGUEL"],
    "BOLIVAR": ["SABANA GRANDE", "CHEREGUE", "GRANADOS"],
    "CANDELARIA": ["CHEJENDE", "ARNOLDO GABALDON", "BOLIVIA", "CARRILLO", "CEGARRA", "MIGUEL VICENTE MOCON", "SAN JOSE"],
    "CARACHE": ["CARACHE", "LA CONCEPCION", "CUICAS", "PANAMERICANA", "SANTA CRUZ"],
    "ESCUQUE": ["ESCUQUE", "LA UNION", "SANTA RITA", "SABANA LIBRE"],
    "JOSE FELIX RIBAS": ["KANGURO", "MACACOLLAR"],
    "JUAN VICENTE CAMPO ELIAS": ["CAMPO ELIAS", "ARNOLDO GABALDON"],
    "LA CEIBA": ["SANTA APOLONIA", "EL PROGRESO", "LA CEIBA", "TRES DE FEBRERO"],
    "MARQUEZ GABILONDO": ["EL DIVIDIVE", "AGUA SANTA", "EL CENIZO", "VALERITA"],
    "MIRANDA": ["AGUA CALIENTE", "EL DIVIDIVE", "EL JAGUITO", "EL CENIZO", "VALERITA"],
    "MONTE CARMELO": ["MONTE CARMELO", "BUENA VISTA", "SANTA MARIA DEL HORCON"],
    "MOTATAN": ["MOTATAN", "EL BANO", "JALISCO"],
    "PAMPAN": ["PAMPAN", "FLOR DE PATRIA", "LA PAZ", "SANTA ANA"],
    "PAMPANITO": ["PAMPANITO", "LA CONCEPCION", "PAMPANITO II"],
    "RAFAEL RANGEL": ["BETIJOQUE", "JOSE GREGORIO HERNANDEZ", "LA PUEBLITA", "LOS CEDROS"],
    "SAN RAFAEL DE CARVAJAL": ["CARVAJAL", "ANTONIO NICOLAS BRICENO", "CAMPO ALEGRE", "JOSE LEONARDO SUAREZ"],
    "SUCRE": ["SABANA DE MENDOZA", "JUNIN", "VALMORE RODRIGUEZ", "EL PARAISO"],
    "TRUJILLO": ["ANDRES LINARES", "CHIQUINQUIRA", "CRISTOBAL MENDOZA", "CRUZ CARRILLO", "MATRIZ", "MONSEÑOR CARRILLO", "TRES ESQUINAS"],
    "URDANETA": ["LA QUEBRADA", "CABIMBU", "JAJO", "LA MESA DE ESPUJA", "SANTIAGO", "TUPURE"],
    "VALERA": ["MERCEDES DIAZ", "JUAN IGNACIO MONTILLA", "LA BEATRIZ", "MENDOZA", "SAN LUIS"]
  },
  "VARGAS": {
    "VARGAS": ["CARABALLEDA", "CARAYACA", "CARLOS SOUBLETTE", "CATIA LA MAR", "EL JUNCKO", "LA GUAIRA", "MACUTO", "MAIQUETIA", "NAIGUATA", "URIA"]
  },
  "YARACUY": {
    "ARISTIDES BASTIDAS": ["SAN PABLO"],
    "BOLIVAR": ["AROA"],
    "BRUZUAL": ["CHIVACOA", "CAMPO ELIAS"],
    "COCOROTE": ["COCOROTE"],
    "INDEPENDENCIA": ["INDEPENDENCIA"],
    "JOSE ANTONIO PAEZ": ["SABANA DE PARRA"],
    "LA TRINIDAD": ["BORAURE"],
    "MANUEL MONGE": ["YUMARE"],
    "NIRGUA": ["NIRGUA", "SALOM", "TEMERLA"],
    "PENA": ["YARITAGUA", "SAN ANDRES"],
    "SAN FELIPE": ["SAN FELIPE", "ALBARICO", "SAN JAVIER"],
    "SUCRE": ["GUAMA"],
    "URACHICHE": ["URACHICHE"],
    "VEROES": ["EL GUAYABO"]
  },
  "ZULIA": {
    "ALMIRANTE PADILLA": ["ISLA DE TOAS", "MONAGAS"],
    "BARALT": ["SAN TIMOTEO", "GENERAL URDANETA", "LIBERTADOR", "MARCELINO BRICENO", "NUEVO OROPEN", "PUEBLO NUEVO"],
    "CABIMAS": ["AMBROSIO", "CARMEN HERRERA", "LA ROSA", "GERMAN RIOS LINARES", "SAN BENITO", "ROMULO BETANCOURT", "JORGE HERNANDEZ", "PUNTA GORDA", "ARISTIDES CALVANI"],
    "CATATUMBO": ["ENCONTRADOS", "UDON PEREZ"],
    "COLON": ["SAN CARLOS DEL ZULIA", "SANTA CRUZ DEL ZULIA", "MORALITO", "SAN JOSE", "URRIBARRI"],
    "FRANCISCO JAVIER PULGAR": ["PUEBLO NUEVO EL CHIVO", "SIMON RODRIGUEZ", "AGUSTIN CODAZZI", "CARLOS QUEVEDO"],
    "GUAJIRA": ["SINAMAICA", "ALTA GUAJIRA", "ELIAS SANCHEZ RUBIO", "GUAJIRA"],
    "JESUS ENRIQUE LOSADA": ["LA CONCEPCION", "SAN JOSE", "MARIANO PARRA LEON", "JOSE RAMON YEPEZ"],
    "JESUS MARIA SEMPRUN": ["CASIGUA EL CUBO", "BARI"],
    "LA CANADA DE URDANETA": ["CONCEPCION", "ANDRES BELLO", "CHIQUINQUIRA", "EL CARMELO", "POTRERITOS"],
    "LAGUNILLAS": ["ALONSO DE OJEDA", "LIBERTAD", "CAMPO LARA", "ELEAZAR LOPEZ CONTRERAS", "VENEZUELA"],
    "MACHIQUES DE PERIJA": ["LIBERTAD", "BARTOLOME DE LAS CASAS", "RIO NEGRO", "SAN JOSE DE PERIJA"],
    "MARA": ["SAN RAFAEL", "LAS PARCELAS", "LUIS DE VICENTE", "MONSENOR MARCOS SERGIO GODOY", "RICAURTE", "SIBARUCAR"],
    "MARACAIBO": ["ANTONIO BORJAS ROMERO", "BOLIVAR", "CACIQUE MARA", "CARRACCIOLO PARRA PEREZ", "CECILIO ACOSTA", "CRISTO DE ARANZA", "COQUIVACOA", "CHIQUINQUIRA", "IDELFONSO VASQUEZ", "FRANCISCO EUGENIO BUSTAMANTE", "JUANA DE AVILA", "LUIS HURTADO HIGUERA", "MANUEL DAGNINO", "OLEGARIO VILLALOBOS", "RAUL LEONI", "SAN ISIDRO", "SANTA LUCIA", "VENANCIO PULGAR"],
    "MIRANDA": ["ALTAGRACIA", "FARIA", "ANA MARIA CAMPOS", "SAN ANTONIO", "SAN JOSE"],
    "ROSARIO DE PERIJA": ["EL ROSARIO", "DONALDO GARCIA", "SIERRA PERIJA"],
    "SAN FRANCISCO": ["SAN FRANCISCO", "EL BAJO", "DOMITILA FLORES", "FRANCISCO OCHOA", "LOS CORTIJOS", "MARCIAL HERANDEZ", "JOSE DOMINGO RUS"],
    "SANTA RITA": ["SANTA RITA", "EL MENE", "PEDRO LUCAS URRIBARRI", "JOSE CENOVIO URRIBARRI"],
    "SIMON BOLIVAR": ["MANUEL MANRIQUE", "RAFAEL MARIA BARALT", "RAFAEL URDANETA"],
    "SUCRE": ["BOBURES", "GIBRALTAR", "HERAS", "MONSENOR ARTURO CELESTINO ALVAREZ", "ROMULO GALLEGOS", "EL BATEY"]
  }
};

export const MUNICIPIOS_ANZOATEGUI = GEOGRAFIA_VENEZUELA["ANZOATEGUI"];
